//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fargo_DataAccessLayers
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKING_DAY_END_TRANSACTION
    {
        public long BOOKING_DAY_END_TRANSACTION_ID { get; set; }
        public Nullable<long> STORE_ID { get; set; }
        public Nullable<long> CASHIER_ID { get; set; }
        public Nullable<bool> IS_CASHIER_APPROVED { get; set; }
        public string CASHIER_REMARK { get; set; }
        public Nullable<double> TOTAL_AMOUNT { get; set; }
        public Nullable<long> MANAGER_ID { get; set; }
        public Nullable<bool> IS_MANAGER_APPROVED { get; set; }
        public string MANAGER_REMARK { get; set; }
        public string STATUS { get; set; }
        public string DATA_SOURCE { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
        public Nullable<long> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<long> MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public Nullable<long> DELETED_BY { get; set; }
        public Nullable<System.DateTime> DELETED_ON { get; set; }
    }
}
