//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fargo_DataAccessLayers
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLE_MASTER
    {
        public long ROLE_ID { get; set; }
        public string ROLE_NAME { get; set; }
        public string ROLE_CODE { get; set; }
        public string LEVEL { get; set; }
        public string HIERARCHY { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<long> PARENT_ROLE_ID { get; set; }
        public string DATA_SOURCE { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
        public Nullable<long> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<long> MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public Nullable<long> DELETED_BY { get; set; }
        public Nullable<System.DateTime> DELETED_ON { get; set; }
    }
}
